#!/usr/bin/env bash

export DISPLAY=:99.0
/etc/init.d/xvfb start

cd test && npm start &

PID=$!                    # get the Parent Process ID
PGID=$(ps opgid= "$PID")  # get the Process Group ID

until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
    printf '.'
    sleep 5
done

NODE_ENV=integration ./node_modules/.bin/ghostjs --ghost-runner slimerjs-core $(find src -name '*.ghost.js')
STATUS=$?

# Kill the process group and all children of that process group.
kill -- -$PGID

exit $STATUS
