#!/usr/bin/env node

/* eslint-env node */
/* eslint no-console:0 */

console.log(`/*
This file was generated by running

    $ ./scripts/whitespace.js

*/`);

console.log(`
:root {
    --hbt: 3px;
    --vbt: 3px;
    --sm-hbt: 4px;
    --sm-vbt: 4px;
    --md-hbt: 8px;
    --md-vbt: 6px;
    --lg-hbt: 8px;
    --lg-vbt: 6px;
}
`);

var breakpoints = ['', 'sm', 'md', 'lg'];
var scale = [0, 1, 2, 3, 4];

function margins(i, hbt, vbt) {
    return `.m${i} {
    margin: ${vbt} ${hbt};
}

.mt${i} {
    margin-top: ${vbt};
}

.mr${i} {
    margin-right: ${hbt};
}

.mb${i} {
    margin-bottom: ${vbt};
}

.ml${i} {
    margin-left: ${hbt};
}`;
}


function negativeMargins(i, nhbt, nvbt) {
    return `
.mxn${i} {
    margin-left: ${nhbt};
    margin-right: ${nhbt};
}

.myn${i} {
    margin-bottom: ${nvbt};
    margin-top: ${nvbt};
}`;
}

function padding(i, hbt, vbt) {
    return `
.p${i} {
    padding: ${vbt} ${hbt};
}

.px${i} {
    padding-left: ${hbt};
    padding-right: ${hbt};
}

.py${i} {
    padding-bottom: ${vbt};
    padding-top: ${vbt};
}`;
}

function indent(str) {
    return str.split('\n').map(function(line) {
        if (line !== '') {
            return '    ' + line;
        } else {
            return line;
        }
    }).join('\n');
}

breakpoints.forEach(function(breakpoint) {
    var rules = scale.reduce(function(rules, i) {
        /* 0 * 0 = 0, so skip writing out the rules */
        if (breakpoint !== '' && i === 0) {
            return rules;
        }

        var prefix = breakpoint === '' ? '' : `${breakpoint}-`;
        var hbt = `calc(var(--${prefix}hbt) * ${i})`;
        var vbt = `calc(var(--${prefix}vbt) * ${i})`;

        var nhbt = `calc(0 - ${hbt})`;
        var nvbt = `calc(0 - ${vbt})`;

        // Margins
        rules.push(margins(i, hbt, vbt));

        // Negative margins
        if (i !== 0) {
            rules.push(negativeMargins(i, nhbt, nvbt));
        }

        // Padding
        rules.push(padding(i, hbt, vbt));

        rules.push('');

        return rules;
    }, []).join('\n');

    if (breakpoint !== '') {
        console.log(`@media (--${breakpoint}) {`);
        console.log(indent(rules));
        console.log('}\n');
    } else {
        console.log(rules);
    }
});
